import { people01, people02,} from '../../assets';

const data = [
  {
    id: 1,
    fullName: "helo world",
    designation: "js",
    gender: "male",
    img: people02,
    teamName: "TeamA",
  },
  {
    id: 2,
    fullName: "hallo world",
    designation: "nodejs",
    gender: "female",
    img: people01,
    teamName: "TeamA",
  },
  {
    id: 3,
    fullName: "heo world",
    designation: "Rjs",
    gender: "male",
    img: people02,
    teamName: "TeamA",
  },
  {
    id: 4,
    fullName: "hllo rld",
    designation: "js",
    gender: "female",
    img: people01,
    teamName: "TeamB",
  },
  {
    id: 5,
    fullName: "hello world",
    designation: ".Net",
    gender: "male",
    img: people02,
    teamName: "TeamB",
  },
  {
    id: 6,
    fullName: "hello world",
    designation: "js",
    gender: "female",
    img: people01,
    teamName: "TeamB",
  },
  {
    id: 7,
    fullName: "ello worl",
    designation: "pyton",
    gender: "male",
    img: people02,
    teamName: "TeamC",
  },
  {
    id: 8,
    fullName: "ello orld",
    designation: "adobejs",
    gender: "female",
    img: people01,
    teamName: "TeamC",
  },
  {
    id: 9,
    fullName: "hllo word",
    designation: "html",
    gender: "male",
    img: people02,
    teamName: "TeamC",
  },
  {
    id: 10,
    fullName: "hell word",
    designation: "js",
    gender: "female",
    img: people01,
    teamName: "TeamC",
  },
  {
    id: 11,
    fullName: "helo wrld",
    designation: "js",
    gender: "male",
    img: people02,
    teamName: "TeamD",
  },
  {
    id: 12,
    fullName: "hello worl",
    designation: "boostrapjs",
    gender: "male",
    img: people02,
    teamName: "TeamD",
  },
  {
    id: 13,
    fullName: "hello word",
    designation: "js",
    gender: "female",
    img: people01,
    teamName: "TeamD",
  },
  {
    id: 14,
    fullName: "hello wold",
    designation: "js",
    gender: "male",
    img: people02,
    teamName: "TeamD",
  },
  {
    id: 15,
    fullName: "hello wrld",
    designation: "js",
    gender: "female",
    img: people01,
    teamName: "TeamD",
  },
  {
    id: 16,
    fullName: "hello orld",
    designation: "js",
    gender: "male",
    img: people02,
    teamName: "TeamA",
  },
];

export default data;